[package]
name = "haversine_calculator"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
lazy_static = "1.5.0"
rand = "0.8.5"
counter = { version = "0.1", path = "./counter" }

[features]
default = ["bench"]
bench = []